{% set version = "1.4.5" %}
{% set sha_value = "13f54e7399b56df6b40666412f2aac7cf99bd197dc51497ce99689e98ecbf333" %}
#NB get sha256 with: curl -sL <URL> | openssl sha256

package:
  name: cif2hkl
  version: {{ version }}

source:
  url: https://gitlab.com/soleil-data-treatment/soleil-software-projects/cif2hkl/-/archive/v{{ version }}/cif2hkl-v{{ version }}.tar.gz
  sha256: {{ sha_value }}
  folder: src

build:
  number: 1

requirements:
  build:
    - cmake
    - make
    - m2w64-gcc-fortran  # [win]
    - {{ compiler('fortran') }}  # [not win]
    - {{ stdlib('c') }}
  run:
    - m2w64-gcc-libgfortran  # [win]


test:
  commands:
    - cif2hkl --help

about:
  home: https://gitlab.com/soleil-data-treatment/soleil-software-projects/cif2hkl
  summary: A program that computes structure factors for neutrons, x-rays, and electrons.
  description: |
    Convert a CIF/CFL/SHX/PCR crystallographic description into a HKL F^2 reflection list.
    A program that computes structure factors for neutrons, x-rays, and electrons.
    This is useful to compute the diffraction pattern from materials.
  license: GPL-3.0-only
  license_family: GPL3
  license_file: src/LICENSE
  doc_url: https://gitlab.com/soleil-data-treatment/soleil-software-projects/cif2hkl
  dev_url: https://gitlab.com/soleil-data-treatment/soleil-software-projects/cif2hkl

extra:
  recipe-maintainers:
    - farhi
    - tkittel
    - willend
