{% set version = "1.4.3" %}
{% set sha_value = "e9b727a09d94fbd1d27a2b8e667a22927d85e4eea3ab77a212552bef6eb06459" %}
#NB get sha256 with: curl -sL <URL> | openssl sha256

package:
  name: cif2hkl
  version: {{ version }}

source:
  url: https://gitlab.com/soleil-data-treatment/soleil-software-projects/cif2hkl/-/archive/v{{ version }}/cif2hkl-v{{ version }}.tar.gz
  sha256: {{ sha_value }}
  folder: src

build:
  number: 2
  skip: True  # [win]

requirements:
  build:
    - cmake
    - make  # [not win]
    - {{ compiler('fortran') }}

test:
  commands:
    - cif2hkl --help

about:
  home: https://gitlab.com/soleil-data-treatment/soleil-software-projects/cif2hkl
  summary: A program that computes structure factors for neutrons, x-rays, and electrons.
  description: |
    Convert a CIF/CFL/SHX/PCR crystallographic description into a HKL F^2 reflection list.
    A program that computes structure factors for neutrons, x-rays, and electrons.
    This is useful to compute the diffraction pattern from materials.
  license: GPL-3.0-only
  license_family: GPL3
  license_file: src/LICENSE
  doc_url: https://gitlab.com/soleil-data-treatment/soleil-software-projects/cif2hkl
  dev_url: https://gitlab.com/soleil-data-treatment/soleil-software-projects/cif2hkl

extra:
  recipe-maintainers:
    - farhi
    - tkittel
    - willend
